baseURL = "https://gabeduke.github.io/blog"
languageCode = "en-us"
title = "Adventures in over-engineering"
canonifyurls = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Adventures in over-engineering"
  keywords = "iot, kubernetes, linux"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "/posts/"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Adventures in over-engineering"
    subtitle = "IOT Sensor Fleet"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd $HOME"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"