baseURL = "https://gabeduke.github.io/blog"
languageCode = "en-us"
title = "Adventures in over-engineering"
canonifyurls = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Gabriel Duke"

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Adventures in over-engineering"
  keywords = "iot, kubernetes, linux"
  images = [""]

  homeSubtitle = "Exploration of Linux, Kubernetes, and all things Computronics"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "/posts/"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  # Social icons

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sudoDuke"

  [[params.social]]
    name = "email"
    url  = "mailto:gabeduke@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/gabeduke"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/gabriel-duke-76ba7b85/"

  # [[params.social]]
  #   name = "stackoverflow"
  #   url  = "https://www.stackoverflow.com/"

[languages]
  [languages.en]
    title = "Adventures in over-engineering"
    subtitle = "IOT Sensor Fleet"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      # logoText = "cd /home/"
      logoText = "cd $HOME"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"